name: ecommerce
description: "E-Commerce App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  #  DateTime
  jiffy: ^6.2.1
  intl: ^0.18.1
  http: ^1.2.1
  #  Images
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  #  Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.2.0
  #  Google Map
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  #  Firebase And Notification
  firebase_messaging: ^11.2.7
  firebase_core: ^1.12.0
  flutter_local_notifications: ^16.3.2
  cloud_firestore: ^3.1.9
  #  Local Data Cache
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  path: ^1.9.0
  #  Qrcode
  qr_flutter: ^4.1.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.2.5
  dropdown_search: ^5.0.6
  badges: ^3.1.2
  #  Icon
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  #  Google Auth
  google_sign_in: ^6.2.1
  device_preview: ^1.1.0
  responsive_builder: ^0.7.0
  image_pickers: ^2.0.4+8
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\PlayfairDisplay\PlayfairDisplay-Black.ttf
          weight: 900

        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets\fonts\PlayfairDisplay\PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic
